### PR TITLE
Add Atom feeds for posts and events

### LINKED ISSUE #69: Add Atom/RSS feed for news items and events
As a user of feed reader software and member of the NL-RSE community, I would like to have posts and events pop up in my feed reader through an Atom or RSS feed. It would be awesome if events were published in an iCalendar-feed as well.

The webpages suggest that there is a feed at `/feed.xml`, but there is no resource there.

### PR DESCRIPTION
**Pull request by bencomp**
This fixes #69. Using the [jekyll-feed plugin](https://github.com/jekyll/jekyll-feed), which is available by default on GitHub, this change builds two Atom feeds – one for the posts (at `/feed.xml`) and one for the events (at `/feed/events.xml`).
Personally I don't mind having separate feeds, but the Minima theme's `head.html` doesn't know about the Events feed and happily outputs a link to `/feed.xml` on the Events page. I would like to fix that before making this PR 'ready'.

Note that the Atom feed lists `nl-rse` as the author of the feeds and all feed entries, because the posts and events do not have authors in the frontmatter. Jekyll Feed therefore uses the site's author from `_config.yml`.

To be able to build the site on my machine, I had to update the `github-pages` group of gems. This updated the Gemfile.lock and introduces the same change as #74; i.e. this PR may interfere with that PR.
After building I found there was no `.gitignore` file, so all output files were considered untracked.

Jekyll presented a warning about the items to be excluded: they should be in a list. I updated the configuration to fix this.

### CODE REVIEW

**Comment by bencomp** [comment]
The jekyll-feed plugin currently only outputs links to the main feed: https://github.com/jekyll/jekyll-feed/issues/334
If necessary, I can try to find a work-around.

**Comment by c-martinez** [comment]
Hi @bencomp!

Great, thanks for this. Thank you for contributing!

I think `nl-rse` being listed as author of the feed is not an issue. I don't have a strong opinion whether there should be separate feeds -- the volume of items published will not be that large anyway.

Can you ping me when you think this PR is ready to be merged? I will happily test it and merge it then.

**Comment by bencomp** [comment]
The thing about separate feeds is that they should all be discoverable. The plugin (or theme) already produces a `<link>` to the posts feed, but the events feed had to be included manually. I did this by overriding the theme's head.html. This means that the events feed will be linked on all pages.

**Comment by c-martinez** [comment]
Thanks @bencomp! This seems to be working fine and is ready to merge.

One thing we should keep in mind -- when we update the website, we should make sure the streams still work. I will try to keep you in the loop when start working on updates :-)

Thanks again!

**Pull request merged**
