### PR TITLE
first version of a minimal website

### PR DESCRIPTION
**Pull request by benvanwerkhoven**
I've tried to create a very minimal website using Jekyll and GitHub pages that will be easy to maintain. The site contains most of the basic info that we discussed in the last meeting. Currently the only things that's missing is info about the (to be created) slack channel.

You can browse this version of the website here: https://benvanwerkhoven.github.io/nl-rse.github.io/

### CODE REVIEW

**Comment by tbkkr** [comment]
Very nice indeed! Shall I ask UK-RSE if we can use their logo (for now) for our website? 

Second thing: between paragraph 1 and 2, add a 'sign up' link on the landing page? I had to search a bit before I found the sign up link now. So:

In bold (and perhaps +1 font size): To join the Dutch RSE community, simply click here [underline] and subscribe to the mailinglist.

**Comment by nielsdrost** [comment]
Agree with the signup on the front page.

Perhaps Ben should ask, he made the site ;-)

**Comment by tbkkr** [comment]
sure!

Van: Niels Drost [mailto:notifications@github.com]
Verzonden: donderdag 18 mei 2017 10:32
Aan: nl-rse/nl-rse.github.io <nl-rse.github.io@noreply.github.com>
CC: Tom Bakker <t.bakker@esciencecenter.nl>; Review requested <review_requested@noreply.github.com>
Onderwerp: Re: [nl-rse/nl-rse.github.io] first version of a minimal website (#1)


Agree with the signup on the front page.

Perhaps Ben should ask, he made the site ;-)

**Comment by tbkkr** [comment]
So, given UK-RSE's positive reponse: shall we merge and put Ben's version online?

**Pull request merged**
